export const text = {
    project1: {
        title: "Hodadoc",
        type: "Develop",
        githubPage: "https://hyungyeong77.github.io/hodadoc",
        github: "https://github.com/HyunGyeong77/hodadoc",
        language: ["Next.js", "React", "SCSS", "TS"],
        content: ["[개발중]", "반응형", "Interactive"],
        video: "/assets/videos/project1.mp4",
    },
    project2: {
        title: "JBFG",
        type: "Clone",
        githubPage: "https://hyungyeong77.github.io/jbfg",
        github: "https://github.com/HyunGyeong77/jbfg",
        language: ["Next.js", "React", "SCSS", "TS"],
        content: ["반응형", "Interactive"],
        video: "/assets/videos/project2.mp4",
    },
    project3: {
        title: "Starbucks",
        type: "Clone",
        githubPage: "https://hyungyeong77.github.io/starbucks",
        github: "https://github.com/HyunGyeong77/starbucks",
        language: ["React", "SCSS", "TS"],
        content: ["반응형", "Interactive"],
        video: "/assets/videos/project3.mp4",
    },
    project4: {
        title: "Jwimovie",
        type: "Develop",
        githubPage: "https://hyungyeong77.github.io/jwimovie",
        github: "https://github.com/HyunGyeong77/jwimovie",
        language: ["React", "SCSS", "TS"],
        content: ["고정형", "Interactive"],
        video: "/assets/videos/project4.mp4",
    },
    project5: {
        title: "Sweat",
        type: "Develop",
        githubPage: "https://hyungyeong77.github.io/sweat",
        github: "https://github.com/HyunGyeong77/sweat",
        language: ["React", "CSS", "SCSS", "TS"],
        content: ["반응형", "Interactive"],
        video: "/assets/videos/project5.mp4",
    },
}